/*
 
 ECS 175: Computer Graphics
 UC Davis, Spring 2013
 
 Project 4
 
 */
#ifndef _BUILDINGSENUM_H_
#define _BUILDINGSENUM_H_

namespace Building_types
{
	/*
	enum building_types {
		ROUND_CAKE,
		SQUARE_CAKE,
		PYRAMID_CAKE,
		CUBE_CORP_SMALL,
		CUBE_CORP_MEDIUM,
		CUBE_CORP_LARGE,
		CYLINDER_CORP_SMALL,
		CYLINDER_CORP_MEDIUM,
		CYLINDER_CORP_LARGE,
		PYRAMID_CORP_SMALL,
		PYRAMID_CORP_MEDIUM,
		PYRAMID_CORP_LARGE,
		ELLIPSE_CORP_SMALL,
		ELLIPSE_CORP_MEDIUM,
		ELLIPSE_CORP_LARGE,
		PYRAMID_CUBE_SMALL,
		PYRAMID_CUBE_MEDIUM,
		PYRAMID_CUBE_LARGE,
		CROSS_SMALL,
		CROSS_MEDIUM,
		CROSS_LARGE,
		SONY_JAPAN_SMALL,
		SONY_JAPAN_MEDIUM,
		SONY_JAPAN_LARGE
	};
	*/

	enum building_types {
		CUBE_CORP_SMALL,
		CYLINDER_CORP_SMALL,
		//PYRAMID_CORP_SMALL,
		ELLIPSE_CORP_SMALL,
		PYRAMID_CUBE_SMALL,
		CUBE_CORP_MEDIUM,
		CYLINDER_CORP_MEDIUM,
		//PYRAMID_CORP_MEDIUM,
		ELLIPSE_CORP_MEDIUM,
		PYRAMID_CUBE_MEDIUM,
		ROUND_CAKE,
		SQUARE_CAKE,
		//PYRAMID_CAKE,
		CUBE_CORP_LARGE,
		CYLINDER_CORP_LARGE,
		//PYRAMID_CORP_LARGE,
		ELLIPSE_CORP_LARGE,
		PYRAMID_CUBE_LARGE,
		CROSS_SMALL,
		SONY_JAPAN_SMALL,
		CROSS_MEDIUM,
		SONY_JAPAN_MEDIUM,
		CROSS_LARGE,
		SONY_JAPAN_LARGE,
		MAILBOX
	};
}

#endif

